[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
RAILS_ENV = "production"
RAILS_LOG_TO_STDOUT = "true"
RAILS_SERVE_STATIC_FILES = "true"
PORT = "3000"
BUNDLE_WITHOUT = "development:test"
RAILS_MAX_THREADS = "5"
WEB_CONCURRENCY = "2"
